<a href="https://colab.research.google.com/github/Kaini9/Data-Analytics-Training/blob/main/Pandas/self-practice/Conditional_self_practice_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df= pd.read_csv('/content/big4_financial_risk_compliance.csv')
df.head(10)

,Year,Firm_Name,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
0,2020,PwC,2829,51,123,39,Healthcare,114.24,No,57,5.8,8.4
1,2022,Deloitte,3589,185,30,60,Healthcare,156.98,Yes,58,5.3,6.7
2,2020,PwC,2438,212,124,97,Healthcare,131.83,No,76,6.1,6.2
3,2021,PwC,2646,397,55,97,Healthcare,229.11,No,60,5.1,8.6
4,2020,PwC,2680,216,99,46,Healthcare,48.00,No,51,9.1,6.7
5,2023,Deloitte,818,448,10,30,Finance,438.89,No,73,5.3,7.1
6,2022,Deloitte,1199,148,114,11,Retail,468.82,No,53,9.6,6.3
7,2020,PwC,4092,500,152,69,Tech,53.85,Yes,80,9.4,9.5
8,2021,PwC,4156,362,53,95,Finance,318.79,No,56,6.0,6.0
9,2021,Ernst & Young,2490,74,144,22,Retail,461.33,Yes,66,6.8,7.3

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       100 non-null    int64
 1   Firm_Name                  100 non-null    object
 2   Total_Audit_Engagements    100 non-null    int64
 3   High_Risk_Cases            100 non-null    int64
 4   Compliance_Violations      100 non-null    int64
 5   Fraud_Cases_Detected       100 non-null    int64
 6   Industry_Affected          100 non-null    object
 7   Total_Revenue_Impact       100 non-null    float64
 8   AI_Used_for_Auditing       100 non-null    object
 9   Employee_Workload          100 non-null    int64
 10  Audit_Effectiveness_Score  100 non-null    float64
 11  Client_Satisfaction_Score  100 non-null    float64
dtypes: float64(3), int64(6), object(3)
memory usage: 9.5+ KB

In [46]:
df.describe()

,Year,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Total_Revenue_Impact,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,2022.320000,2784.520000,277.730000,105.480000,52.700000,272.539000,60.250000,7.490000,7.339000
std,1.780251,1281.863073,135.735174,55.370101,28.311221,139.151401,11.163048,1.516209,1.429127
min,2020.000000,603.000000,51.000000,10.000000,5.000000,33.460000,40.000000,5.000000,5.000000
25%,2021.000000,1768.250000,162.500000,54.500000,27.000000,155.217500,52.750000,6.100000,6.100000
50%,2022.000000,2650.000000,293.000000,114.500000,54.000000,264.450000,60.000000,7.450000,7.350000
75%,2024.000000,4008.750000,395.500000,149.500000,74.500000,406.090000,68.000000,8.825000,8.525000
max,2025.000000,4946.000000,500.000000,200.000000,100.000000,497.060000,80.000000,10.000000,10.000000

kun company ma employee workload dherai xata ra kun year ma

In [48]:
df.loc[df["Employee_Workload"].max()== df["Employee_Workload"], ["Firm_Name","Employee_Workload","Year"]]

  Firm_Name  Employee_Workload  Year
7       PwC                 80  2020

kun company ko 2024 ma workload 60 above ra highrisk cases dherai thyo

In [52]:
df.loc[(df["Year"]== 2024) & (df["Employee_Workload"]>60 ), ["Firm_Name","Employee_Workload","Year","High_Risk_Cases"]]

        Firm_Name  Employee_Workload  Year  High_Risk_Cases
11  Ernst & Young                 78  2024              408
43           KPMG                 63  2024              442
56  Ernst & Young                 68  2024              306
59       Deloitte                 66  2024              201
68  Ernst & Young                 74  2024              377
77            PwC                 74  2024              391
78            PwC                 62  2024               86

100 vanda badi total revenue impact vako company ko name only in 2024 ma

In [45]:
df.loc[(df["Year"]== 2024) & (df["Total_Revenue_Impact"]> 100), ["Firm_Name","Total_Revenue_Impact","Year"]]

        Firm_Name  Total_Revenue_Impact  Year
11  Ernst & Young                224.92  2024
12       Deloitte                418.49  2024
20       Deloitte                221.42  2024
23  Ernst & Young                291.00  2024
24            PwC                225.42  2024
33  Ernst & Young                156.76  2024
37       Deloitte                284.84  2024
43           KPMG                468.13  2024
56  Ernst & Young                426.07  2024
59       Deloitte                378.30  2024
65       Deloitte                263.14  2024
68  Ernst & Young                193.07  2024
71       Deloitte                268.67  2024
77            PwC                240.87  2024
78            PwC                206.47  2024
88            PwC                362.31  2024

Deloitte ko matra data herum

In [33]:
df.loc[df["Firm_Name"]=="Deloitte", :]

,Year,Firm_Name,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
1,2022,Deloitte,3589,185,30,60,Healthcare,156.98,Yes,58,5.3,6.7
5,2023,Deloitte,818,448,10,30,Finance,438.89,No,73,5.3,7.1
6,2022,Deloitte,1199,148,114,11,Retail,468.82,No,53,9.6,6.3
12,2024,Deloitte,2885,469,125,92,Healthcare,418.49,No,58,9.3,7.7
15,2021,Deloitte,3490,127,17,62,Finance,495.19,Yes,52,8.4,7.5
17,2022,Deloitte,4813,249,81,64,Retail,182.90,No,67,9.8,7.5
18,2022,Deloitte,2804,273,87,36,Healthcare,243.85,No,46,6.6,9.5
20,2024,Deloitte,1581,247,181,72,Retail,221.42,No,56,5.6,7.9
21,2025,Deloitte,760,406,65,69,Finance,140.29,Yes,40,5.1,7.5
30,2020,Deloitte,2030,200,169,18,Healthcare,104.98,No,76,5.2,9.3
34,2022,Deloitte,4287,158,73,66,Healthcare,69.97,No,78,8.3,6.5
37,2024,Deloitte,4324,483,166,26,Healthcare,284.84,No,40,8.8,6.2
39,2021,Deloitte,603,62,100,20,Tech,415.30,Yes,60,5.3,8.5
46,2025,Deloitte,718,360,193,14,Retail,432.80,No,64,7.3,8.9
47,2021,Deloitte,4601,65,196,28,Tech,320.75,No,75,7.7,5.7
51,2025,Deloitte,1695,285,137,61,Tech,302.28,Yes,64,9.1,8.4
52,2020,Deloitte,995,354,126,25,Healthcare,160.31,No,68,9.3,6.2
54,2021,Deloitte,1992,313,74,93,Tech,110.06,No,61,7.6,7.5
57,2025,Deloitte,4390,367,167,51,Tech,334.56,Yes,59,7.8,9.6
59,2024,Deloitte,1275,201,20,100,Retail,378.30,No,66,8.5,7.8
63,2025,Deloitte,2208,296,198,72,Retail,395.59,Yes,77,6.0,6.7
65,2024,Deloitte,2183,449,25,27,Finance,263.14,Yes,48,9.0,8.3
71,2024,Deloitte,4784,382,15,73,Healthcare,268.67,No,59,6.7,10.0
79,2021,Deloitte,3305,226,132,81,Tech,403.02,No,73,5.5,7.6
80,2020,Deloitte,912,481,200,20,Healthcare,83.61,No,66,8.6,9.3
89,2022,Deloitte,962,356,155,21,Finance,54.07,Yes,60,9.1,5.9
90,2020,Deloitte,1925,189,39,52,Tech,118.92,No,70,9.4,6.4
93,2021,Deloitte,797,133,46,27,Finance,474.32,No,77,6.3,8.6
97,2021,Deloitte,3810,463,35,96,Healthcare,349.04,No,55,6.4,6.5
98,2025,Deloitte,1896,110,151,14,Finance,456.08,No,74,8.7,7.1

deloitee ko data tara only 2020 ko matra herum hai ta

In [39]:
df.loc[(df["Firm_Name"]=="Deloitte") & (df["Year"] == 2020),:]

,Year,Firm_Name,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
30,2020,Deloitte,2030,200,169,18,Healthcare,104.98,No,76,5.2,9.3
52,2020,Deloitte,995,354,126,25,Healthcare,160.31,No,68,9.3,6.2
80,2020,Deloitte,912,481,200,20,Healthcare,83.61,No,66,8.6,9.3
90,2020,Deloitte,1925,189,39,52,Tech,118.92,No,70,9.4,6.4

healthcare affect vako company 2022 ma

In [44]:
df.loc[(df["Industry_Affected"]=="Healthcare") & (df["Year"] == 2020),"Firm_Name"]

0               PwC
2               PwC
4               PwC
30         Deloitte
31    Ernst & Young
52         Deloitte
80         Deloitte
Name: Firm_Name, dtype: object

15 vanda badi fraud cases vako company in 2020

In [41]:
df.loc[(df["Year"]== 2020) & (df["Fraud_Cases_Detected"]> 15), ["Firm_Name","Fraud_Cases_Detected","Year"]]

        Firm_Name  Fraud_Cases_Detected  Year
0             PwC                    39  2020
2             PwC                    97  2020
4             PwC                    46  2020
7             PwC                    69  2020
14            PwC                    17  2020
16  Ernst & Young                    18  2020
26           KPMG                    94  2020
30       Deloitte                    18  2020
31  Ernst & Young                    94  2020
40            PwC                    63  2020
52       Deloitte                    25  2020
58            PwC                    45  2020
61           KPMG                    73  2020
72           KPMG                    71  2020
76  Ernst & Young                    60  2020
80       Deloitte                    20  2020
85            PwC                    66  2020
90       Deloitte                    52  2020
96  Ernst & Young                    59  2020

2020 ma kun ma thorai risk thyo

In [7]:
df.loc[df["Year"]== 2020, ["Firm_Name","High_Risk_Cases","Year"]].min()

Firm_Name          Deloitte
High_Risk_Cases          51
Year                   2020
dtype: object

maximun chai kaslai thyo ta

In [8]:
df.loc[df["Year"]== 2020, ["Firm_Name","High_Risk_Cases","Year"]].max()

Firm_Name           PwC
High_Risk_Cases     500
Year               2020
dtype: object

kun company lai kun barsa dherai risk

In [14]:
df.loc[df.groupby("Year")["High_Risk_Cases"].idxmax(),["Year", "Firm_Name", "High_Risk_Cases"]].sort_values("Firm_Name")

    Year      Firm_Name  High_Risk_Cases
97  2021       Deloitte              463
37  2024       Deloitte              483
28  2025  Ernst & Young              497
66  2022           KPMG              487
91  2023           KPMG              453
7   2020            PwC              500

kun barsa ma kun firm lai risk dherai?

In [17]:
df.loc[df.groupby("Year")["High_Risk_Cases"].idxmax(),["Year", "Firm_Name", "High_Risk_Cases"]].sort_values("Year")

    Year      Firm_Name  High_Risk_Cases
7   2020            PwC              500
97  2021       Deloitte              463
66  2022           KPMG              487
91  2023           KPMG              453
37  2024       Deloitte              483
28  2025  Ernst & Young              497

2020 ma client satisfaction kasko badi

In [29]:
df.loc[df["Year"] ==2020 ,["Firm_Name","Client_Satisfaction_Score","Year"]].max()

Firm_Name                     PwC
Client_Satisfaction_Score     9.6
Year                         2020
dtype: object

satisfaction kun ko max hola ta sabai barsa ma best

In [27]:
df.loc[df["Client_Satisfaction_Score"].idxmax(),["Year", "Firm_Name", "Client_Satisfaction_Score"]]

Year                             2024
Firm_Name                    Deloitte
Client_Satisfaction_Score        10.0
Name: 71, dtype: object