<a href="https://colab.research.google.com/github/Kaini9/Data-Analytics-Training/blob/main/Pandas/self-practice/Practicing_sorting__set__reset___use_Indexes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
df= pd.read_csv("/content/big4_financial_risk_compliance.csv")

In [7]:
df.head()

,Year,Firm_Name,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
0,2020,PwC,2829,51,123,39,Healthcare,114.24,No,57,5.8,8.4
1,2022,Deloitte,3589,185,30,60,Healthcare,156.98,Yes,58,5.3,6.7
2,2020,PwC,2438,212,124,97,Healthcare,131.83,No,76,6.1,6.2
3,2021,PwC,2646,397,55,97,Healthcare,229.11,No,60,5.1,8.6
4,2020,PwC,2680,216,99,46,Healthcare,48.00,No,51,9.1,6.7

In [8]:
df.describe()

,Year,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Total_Revenue_Impact,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,2022.320000,2784.520000,277.730000,105.480000,52.700000,272.539000,60.250000,7.490000,7.339000
std,1.780251,1281.863073,135.735174,55.370101,28.311221,139.151401,11.163048,1.516209,1.429127
min,2020.000000,603.000000,51.000000,10.000000,5.000000,33.460000,40.000000,5.000000,5.000000
25%,2021.000000,1768.250000,162.500000,54.500000,27.000000,155.217500,52.750000,6.100000,6.100000
50%,2022.000000,2650.000000,293.000000,114.500000,54.000000,264.450000,60.000000,7.450000,7.350000
75%,2024.000000,4008.750000,395.500000,149.500000,74.500000,406.090000,68.000000,8.825000,8.525000
max,2025.000000,4946.000000,500.000000,200.000000,100.000000,497.060000,80.000000,10.000000,10.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       100 non-null    int64
 1   Firm_Name                  100 non-null    object
 2   Total_Audit_Engagements    100 non-null    int64
 3   High_Risk_Cases            100 non-null    int64
 4   Compliance_Violations      100 non-null    int64
 5   Fraud_Cases_Detected       100 non-null    int64
 6   Industry_Affected          100 non-null    object
 7   Total_Revenue_Impact       100 non-null    float64
 8   AI_Used_for_Auditing       100 non-null    object
 9   Employee_Workload          100 non-null    int64
 10  Audit_Effectiveness_Score  100 non-null    float64
 11  Client_Satisfaction_Score  100 non-null    float64
dtypes: float64(3), int64(6), object(3)
memory usage: 9.5+ KB

SORTING

LA FRAUD CASES ANUSAR SORT GARAM

In [10]:
df.sort_values(by="Fraud_Cases_Detected")

,Year,Firm_Name,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
75,2021,PwC,1078,395,58,5,Tech,139.48,Yes,62,7.3,5.9
45,2020,Ernst & Young,4570,284,155,6,Tech,389.37,No,52,6.1,6.1
94,2023,Ernst & Young,4895,123,132,10,Tech,389.31,No,48,9.3,8.4
10,2020,KPMG,1497,330,10,10,Finance,258.49,Yes,59,8.3,8.0
23,2024,Ernst & Young,1760,415,183,11,Healthcare,291.00,Yes,53,8.2,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...
97,2021,Deloitte,3810,463,35,96,Healthcare,349.04,No,55,6.4,6.5
3,2021,PwC,2646,397,55,97,Healthcare,229.11,No,60,5.1,8.6
2,2020,PwC,2438,212,124,97,Healthcare,131.83,No,76,6.1,6.2
91,2023,KPMG,2919,453,35,99,Tech,95.68,Yes,47,8.0,5.1
59,2024,Deloitte,1275,201,20,100,Retail,378.30,No,66,8.5,7.8

LA ABA FRAUD CASES LAI DESENDING MA HERUM HAI TA

In [12]:
df.sort_values(by="Fraud_Cases_Detected",  ascending=False)

,Year,Firm_Name,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
59,2024,Deloitte,1275,201,20,100,Retail,378.30,No,66,8.5,7.8
91,2023,KPMG,2919,453,35,99,Tech,95.68,Yes,47,8.0,5.1
3,2021,PwC,2646,397,55,97,Healthcare,229.11,No,60,5.1,8.6
2,2020,PwC,2438,212,124,97,Healthcare,131.83,No,76,6.1,6.2
97,2021,Deloitte,3810,463,35,96,Healthcare,349.04,No,55,6.4,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...
23,2024,Ernst & Young,1760,415,183,11,Healthcare,291.00,Yes,53,8.2,8.4
10,2020,KPMG,1497,330,10,10,Finance,258.49,Yes,59,8.3,8.0
94,2023,Ernst & Young,4895,123,132,10,Tech,389.31,No,48,9.3,8.4
45,2020,Ernst & Young,4570,284,155,6,Tech,389.37,No,52,6.1,6.1
75,2021,PwC,1078,395,58,5,Tech,139.48,Yes,62,7.3,5.9

ABA FRAUD CASES PAHILA RA TESPAXI Client Satisfaction HAI TA

In [16]:
df.sort_values(by=["Fraud_Cases_Detected","Client_Satisfaction_Score"])

,Year,Firm_Name,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
75,2021,PwC,1078,395,58,5,Tech,139.48,Yes,62,7.3,5.9
45,2020,Ernst & Young,4570,284,155,6,Tech,389.37,No,52,6.1,6.1
10,2020,KPMG,1497,330,10,10,Finance,258.49,Yes,59,8.3,8.0
94,2023,Ernst & Young,4895,123,132,10,Tech,389.31,No,48,9.3,8.4
6,2022,Deloitte,1199,148,114,11,Retail,468.82,No,53,9.6,6.3
...,...,...,...,...,...,...,...,...,...,...,...,...
97,2021,Deloitte,3810,463,35,96,Healthcare,349.04,No,55,6.4,6.5
2,2020,PwC,2438,212,124,97,Healthcare,131.83,No,76,6.1,6.2
3,2021,PwC,2646,397,55,97,Healthcare,229.11,No,60,5.1,8.6
91,2023,KPMG,2919,453,35,99,Tech,95.68,Yes,47,8.0,5.1
59,2024,Deloitte,1275,201,20,100,Retail,378.30,No,66,8.5,7.8

lets check only that two column with name

In [27]:
df[["Fraud_Cases_Detected","Firm_Name", "Client_Satisfaction_Score"]].sort_values(by=["Fraud_Cases_Detected", "Client_Satisfaction_Score"])

    Fraud_Cases_Detected      Firm_Name  Client_Satisfaction_Score
75                     5            PwC                        5.9
45                     6  Ernst & Young                        6.1
10                    10           KPMG                        8.0
94                    10  Ernst & Young                        8.4
6                     11       Deloitte                        6.3
..                   ...            ...                        ...
97                    96       Deloitte                        6.5
2                     97            PwC                        6.2
3                     97            PwC                        8.6
91                    99           KPMG                        5.1
59                   100       Deloitte                        7.8

[100 rows x 3 columns]

Lets sort the indexes

In [80]:
df.sort_index()

,Year,Firm_Name,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
0,2021,Deloitte,603,62,100,20,Tech,415.30,Yes,60,5.3,8.5
1,2020,Deloitte,1925,189,39,52,Tech,118.92,No,70,9.4,6.4
2,2022,Deloitte,962,356,155,21,Finance,54.07,Yes,60,9.1,5.9
3,2020,Deloitte,2030,200,169,18,Healthcare,104.98,No,76,5.2,9.3
4,2022,Deloitte,4287,158,73,66,Healthcare,69.97,No,78,8.3,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2020,PwC,4401,249,126,45,Finance,424.03,No,60,8.2,5.7
96,2023,PwC,2283,58,103,82,Healthcare,168.15,Yes,59,6.7,5.6
97,2021,PwC,1078,395,58,5,Tech,139.48,Yes,62,7.3,5.9
98,2024,PwC,4103,423,179,30,Healthcare,225.42,Yes,41,6.7,5.0
99,2021,PwC,4473,195,199,58,Finance,235.12,Yes,54,6.4,7.4

lets acess deliotee from firm name second by loc iloc

ILOC

3rd row ko colunm ra 1,6 lai print garnum

In [85]:

df.iloc[3, [1, 6]]

Firm_Name              Deloitte
Industry_Affected    Healthcare
Name: 3, dtype: object

In [74]:
df.iloc[1,1]

'Deloitte'

get get 189 from high risk

In [81]:
df.iloc[1,3]

np.int64(189)

by LOC

In [89]:
df.loc[3, ["Firm_Name", "Industry_Affected"]]

Firm_Name              Deloitte
Industry_Affected    Healthcare
Name: 3, dtype: object

In [75]:
df.loc[1,"Firm_Name"]

'Deloitte'

In [82]:
df.loc[1,"High_Risk_Cases"]

np.int64(189)

LETS USE CONDITIONS

In [94]:
df.loc[df["High_Risk_Cases"] >60, ["Firm_Name", "Industry_Affected"]]

   Firm_Name Industry_Affected
0   Deloitte              Tech
1   Deloitte              Tech
2   Deloitte           Finance
3   Deloitte        Healthcare
4   Deloitte        Healthcare
..       ...               ...
94       PwC           Finance
95       PwC           Finance
97       PwC              Tech
98       PwC        Healthcare
99       PwC           Finance

[96 rows x 2 columns]

300 vanda badi risk huda only in deloitte reveneu impact herum

In [103]:
df.loc[(df["Firm_Name"]=="Deloitte") & (df["High_Risk_Cases"]> 300),["Industry_Affected","Firm_Name","High_Risk_Cases","Total_Revenue_Impact"]]

   Industry_Affected Firm_Name  High_Risk_Cases  Total_Revenue_Impact
2            Finance  Deloitte              356                 54.07
5         Healthcare  Deloitte              483                284.84
6         Healthcare  Deloitte              481                 83.61
7             Retail  Deloitte              360                432.80
11        Healthcare  Deloitte              354                160.31
12              Tech  Deloitte              313                110.06
13              Tech  Deloitte              367                334.56
16           Finance  Deloitte              449                263.14
17        Healthcare  Deloitte              382                268.67
18           Finance  Deloitte              406                140.29
23        Healthcare  Deloitte              463                349.04
25        Healthcare  Deloitte              469                418.49
26           Finance  Deloitte              448                438.89

Lets use inplace = true

In [50]:
df.sort_values(by=["Fraud_Cases_Detected", "Client_Satisfaction_Score",],inplace=True)

now it changed perm

In [51]:
df[["Fraud_Cases_Detected","Firm_Name", "Client_Satisfaction_Score"]]

    Fraud_Cases_Detected      Firm_Name  Client_Satisfaction_Score
75                     5            PwC                        5.9
45                     6  Ernst & Young                        6.1
10                    10           KPMG                        8.0
94                    10  Ernst & Young                        8.4
6                     11       Deloitte                        6.3
..                   ...            ...                        ...
97                    96       Deloitte                        6.5
2                     97            PwC                        6.2
3                     97            PwC                        8.6
91                    99           KPMG                        5.1
59                   100       Deloitte                        7.8

[100 rows x 3 columns]

now lets sort by name accending and decending

In [71]:
df.sort_index(inplace=True)

decending

In [72]:
df.sort_values(by="Firm_Name", ascending=False)

,Year,Firm_Name,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
0,2020,PwC,2829,51,123,39,Healthcare,114.24,No,57,5.8,8.4
75,2021,PwC,1078,395,58,5,Tech,139.48,Yes,62,7.3,5.9
25,2025,PwC,4470,63,49,54,Tech,213.92,Yes,43,5.8,5.6
36,2023,PwC,3449,102,61,42,Finance,33.46,Yes,77,5.2,9.2
40,2020,PwC,3981,199,134,63,Tech,52.64,Yes,63,6.8,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...
52,2020,Deloitte,995,354,126,25,Healthcare,160.31,No,68,9.3,6.2
54,2021,Deloitte,1992,313,74,93,Tech,110.06,No,61,7.6,7.5
57,2025,Deloitte,4390,367,167,51,Tech,334.56,Yes,59,7.8,9.6
63,2025,Deloitte,2208,296,198,72,Retail,395.59,Yes,77,6.0,6.7
59,2024,Deloitte,1275,201,20,100,Retail,378.30,No,66,8.5,7.8

In [73]:
df.sort_values(by="Firm_Name", ascending=True)

,Year,Firm_Name,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
39,2021,Deloitte,603,62,100,20,Tech,415.30,Yes,60,5.3,8.5
90,2020,Deloitte,1925,189,39,52,Tech,118.92,No,70,9.4,6.4
89,2022,Deloitte,962,356,155,21,Finance,54.07,Yes,60,9.1,5.9
30,2020,Deloitte,2030,200,169,18,Healthcare,104.98,No,76,5.2,9.3
34,2022,Deloitte,4287,158,73,66,Healthcare,69.97,No,78,8.3,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...
58,2020,PwC,4401,249,126,45,Finance,424.03,No,60,8.2,5.7
70,2023,PwC,2283,58,103,82,Healthcare,168.15,Yes,59,6.7,5.6
75,2021,PwC,1078,395,58,5,Tech,139.48,Yes,62,7.3,5.9
24,2024,PwC,4103,423,179,30,Healthcare,225.42,Yes,41,6.7,5.0
99,2021,PwC,4473,195,199,58,Finance,235.12,Yes,54,6.4,7.4

RESET

index fromm 0  ra name anusar sort

In [76]:
df.sort_values(by="Firm_Name", inplace=True)
df.reset_index(drop=True, inplace=True)

In [77]:
df

,Year,Firm_Name,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
0,2021,Deloitte,603,62,100,20,Tech,415.30,Yes,60,5.3,8.5
1,2020,Deloitte,1925,189,39,52,Tech,118.92,No,70,9.4,6.4
2,2022,Deloitte,962,356,155,21,Finance,54.07,Yes,60,9.1,5.9
3,2020,Deloitte,2030,200,169,18,Healthcare,104.98,No,76,5.2,9.3
4,2022,Deloitte,4287,158,73,66,Healthcare,69.97,No,78,8.3,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2020,PwC,4401,249,126,45,Finance,424.03,No,60,8.2,5.7
96,2023,PwC,2283,58,103,82,Healthcare,168.15,Yes,59,6.7,5.6
97,2021,PwC,1078,395,58,5,Tech,139.48,Yes,62,7.3,5.9
98,2024,PwC,4103,423,179,30,Healthcare,225.42,Yes,41,6.7,5.0
99,2021,PwC,4473,195,199,58,Finance,235.12,Yes,54,6.4,7.4

LETS SET INDEX BY NAME

In [105]:
df.set_index("Firm_Name")

,Year,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
Firm_Name,,,,,,,,,,,
Deloitte,2021,603,62,100,20,Tech,415.30,Yes,60,5.3,8.5
Deloitte,2020,1925,189,39,52,Tech,118.92,No,70,9.4,6.4
Deloitte,2022,962,356,155,21,Finance,54.07,Yes,60,9.1,5.9
Deloitte,2020,2030,200,169,18,Healthcare,104.98,No,76,5.2,9.3
Deloitte,2022,4287,158,73,66,Healthcare,69.97,No,78,8.3,6.5
...,...,...,...,...,...,...,...,...,...,...,...
PwC,2020,4401,249,126,45,Finance,424.03,No,60,8.2,5.7
PwC,2023,2283,58,103,82,Healthcare,168.15,Yes,59,6.7,5.6
PwC,2021,1078,395,58,5,Tech,139.48,Yes,62,7.3,5.9
PwC,2024,4103,423,179,30,Healthcare,225.42,Yes,41,6.7,5.0
PwC,2021,4473,195,199,58,Finance,235.12,Yes,54,6.4,7.4

In [106]:
df

,Year,Firm_Name,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
0,2021,Deloitte,603,62,100,20,Tech,415.30,Yes,60,5.3,8.5
1,2020,Deloitte,1925,189,39,52,Tech,118.92,No,70,9.4,6.4
2,2022,Deloitte,962,356,155,21,Finance,54.07,Yes,60,9.1,5.9
3,2020,Deloitte,2030,200,169,18,Healthcare,104.98,No,76,5.2,9.3
4,2022,Deloitte,4287,158,73,66,Healthcare,69.97,No,78,8.3,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2020,PwC,4401,249,126,45,Finance,424.03,No,60,8.2,5.7
96,2023,PwC,2283,58,103,82,Healthcare,168.15,Yes,59,6.7,5.6
97,2021,PwC,1078,395,58,5,Tech,139.48,Yes,62,7.3,5.9
98,2024,PwC,4103,423,179,30,Healthcare,225.42,Yes,41,6.7,5.0
99,2021,PwC,4473,195,199,58,Finance,235.12,Yes,54,6.4,7.4

PERMANENTLY NOT CHANGED LETS USE INPLACE=TRUE

In [114]:
df.set_index("Firm_Name", inplace=True)

In [115]:
df

,Year,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
Firm_Name,,,,,,,,,,,
Deloitte,2021,603,62,100,20,Tech,415.30,Yes,60,5.3,8.5
Deloitte,2020,1925,189,39,52,Tech,118.92,No,70,9.4,6.4
Deloitte,2022,962,356,155,21,Finance,54.07,Yes,60,9.1,5.9
Deloitte,2020,2030,200,169,18,Healthcare,104.98,No,76,5.2,9.3
Deloitte,2022,4287,158,73,66,Healthcare,69.97,No,78,8.3,6.5
...,...,...,...,...,...,...,...,...,...,...,...
PwC,2020,4401,249,126,45,Finance,424.03,No,60,8.2,5.7
PwC,2023,2283,58,103,82,Healthcare,168.15,Yes,59,6.7,5.6
PwC,2021,1078,395,58,5,Tech,139.48,Yes,62,7.3,5.9
PwC,2024,4103,423,179,30,Healthcare,225.42,Yes,41,6.7,5.0
PwC,2021,4473,195,199,58,Finance,235.12,Yes,54,6.4,7.4

NOW LETS RESET INDEX

In [116]:
df.reset_index(inplace=True)

In [117]:
df

,Firm_Name,Year,Total_Audit_Engagements,High_Risk_Cases,Compliance_Violations,Fraud_Cases_Detected,Industry_Affected,Total_Revenue_Impact,AI_Used_for_Auditing,Employee_Workload,Audit_Effectiveness_Score,Client_Satisfaction_Score
0,Deloitte,2021,603,62,100,20,Tech,415.30,Yes,60,5.3,8.5
1,Deloitte,2020,1925,189,39,52,Tech,118.92,No,70,9.4,6.4
2,Deloitte,2022,962,356,155,21,Finance,54.07,Yes,60,9.1,5.9
3,Deloitte,2020,2030,200,169,18,Healthcare,104.98,No,76,5.2,9.3
4,Deloitte,2022,4287,158,73,66,Healthcare,69.97,No,78,8.3,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...
95,PwC,2020,4401,249,126,45,Finance,424.03,No,60,8.2,5.7
96,PwC,2023,2283,58,103,82,Healthcare,168.15,Yes,59,6.7,5.6
97,PwC,2021,1078,395,58,5,Tech,139.48,Yes,62,7.3,5.9
98,PwC,2024,4103,423,179,30,Healthcare,225.42,Yes,41,6.7,5.0
99,PwC,2021,4473,195,199,58,Finance,235.12,Yes,54,6.4,7.4