<a href="https://colab.research.google.com/github/Kaini9/Data-Analytics-Training/blob/main/Pandas/self-practice/Selfpractice_Addingand_removing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

lets create a dummy dataset to practice adding and removing

In [2]:
#sample dataset creation
data = {
    "Name": ["Saval", "Nischal", "Manil", "Anush"],
    "Age": [22, 19, 25, 20],
    "Gender": ["male", "Male", "male", "male"],
    "Survived": [1, 1, 0, 1],
    "Fare": [50, 100, 30, 60]
}

df = pd.DataFrame(data)
df

      Name  Age Gender  Survived  Fare
0    Saval   22   male         1    50
1  Nischal   19   Male         1   100
2    Manil   25   male         0    30
3    Anush   20   male         1    60

SO now lets try to add a new column, lets add a column named ADDRESS

In [3]:
df.loc[:,"Address"] = ["Nepal","Australia","UAE","USA"]

In [4]:
df

      Name  Age Gender  Survived  Fare    Address
0    Saval   22   male         1    50      Nepal
1  Nischal   19   Male         1   100  Australia
2    Manil   25   male         0    30        UAE
3    Anush   20   male         1    60        USA

lets manupulate the age 5 years back

In [5]:
df.loc[:,"Age_five_yrs_before"]=df["Age"]-5

In [6]:
df

      Name  Age Gender  Survived  Fare    Address  Age_five_yrs_before
0    Saval   22   male         1    50      Nepal                   17
1  Nischal   19   Male         1   100  Australia                   14
2    Manil   25   male         0    30        UAE                   20
3    Anush   20   male         1    60        USA                   15

Lets add adress 5 yr ago where we all were

In [9]:
df.loc[:,"Address_fiveyr_ago"]=["Nepal","Nepal","Nepal","Nepal"]

In [10]:
df

,Name,Age,Gender,Survived,Fare,Address,Age_five_yrs_before,Address_fiveyr_ago
0,Saval,22,male,1,50,Nepal,17,Nepal
1,Nischal,19,Male,1,100,Australia,14,Nepal
2,Manil,25,male,0,30,UAE,20,Nepal
3,Anush,20,male,1,60,USA,15,Nepal

lets add status of all at once as all of us are single

In [14]:
df.loc[:, "Status"]= "Single"

In [15]:
df

,Name,Age,Gender,Survived,Fare,Address,Age_five_yrs_before,Address_fiveyr_ago,Status
0,Saval,22,male,1,50,Nepal,17,Nepal,Single
1,Nischal,19,Male,1,100,Australia,14,Nepal,Single
2,Manil,25,male,0,30,UAE,20,Nepal,Single
3,Anush,20,male,1,60,USA,15,Nepal,Single
":,Status",Single,Single,Single,Single,Single,Single,Single,Single,Single

By mistakenly i added in rows inplace of making new column, So lets remove it by its index using iloc

In [19]:
df = df.iloc[:-1]
df

,Name,Age,Gender,Survived,Fare,Address,Age_five_yrs_before,Address_fiveyr_ago,Status
0,Saval,22,male,1,50,Nepal,17,Nepal,Single
1,Nischal,19,Male,1,100,Australia,14,Nepal,Single
2,Manil,25,male,0,30,UAE,20,Nepal,Single
3,Anush,20,male,1,60,USA,15,Nepal,Single

lets add some tax on fare by 1.6

In [24]:
df.loc[:, "Fare_after_tax"] = df["Fare"] * 1.6

In [25]:
df[["Fare_after_tax","Fare"]]

  Fare_after_tax Fare
0           80.0   50
1          160.0  100
2           48.0   30
3           96.0   60

Now lets try to add new person data to my dataset

In [26]:
df

,Name,Age,Gender,Survived,Fare,Address,Age_five_yrs_before,Address_fiveyr_ago,Status,Fare_after_tax
0,Saval,22,male,1,50,Nepal,17,Nepal,Single,80.0
1,Nischal,19,Male,1,100,Australia,14,Nepal,Single,160.0
2,Manil,25,male,0,30,UAE,20,Nepal,Single,48.0
3,Anush,20,male,1,60,USA,15,Nepal,Single,96.0

In [29]:
df.loc[5]={"Name":"Arpan","Age":22,"Gender":"male"}

/tmp/ipykernel_999/1546869625.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[5]={"Name":"Arpan","Age":22,"Gender":"male"}

In [30]:
df.iloc[4,:]

Name                   Arpan
Age                       22
Gender                  male
Survived                 NaN
Fare                     NaN
Address                  NaN
Age_five_yrs_before      NaN
Address_fiveyr_ago       NaN
Status                   NaN
Fare_after_tax           NaN
Name: 5, dtype: object

Now lets change the specific row for specific columns

In [31]:
df

,Name,Age,Gender,Survived,Fare,Address,Age_five_yrs_before,Address_fiveyr_ago,Status,Fare_after_tax
0,Saval,22,male,1,50,Nepal,17,Nepal,Single,80.0
1,Nischal,19,Male,1,100,Australia,14,Nepal,Single,160.0
2,Manil,25,male,0,30,UAE,20,Nepal,Single,48.0
3,Anush,20,male,1,60,USA,15,Nepal,Single,96.0
5,Arpan,22,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN

lets change survide for manil to 1

In [32]:
df.loc[df["Name"]=="Manil","Survived"]=1

In [33]:
df

,Name,Age,Gender,Survived,Fare,Address,Age_five_yrs_before,Address_fiveyr_ago,Status,Fare_after_tax
0,Saval,22,male,1,50,Nepal,17,Nepal,Single,80.0
1,Nischal,19,Male,1,100,Australia,14,Nepal,Single,160.0
2,Manil,25,male,1,30,UAE,20,Nepal,Single,48.0
3,Anush,20,male,1,60,USA,15,Nepal,Single,96.0
5,Arpan,22,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN

now lets try for multiple columns for arpan

In [35]:
df.loc[df['Name'] == 'Arpan', ['Address', 'Gender', 'Status']] = ["Nepal", 'male', 'Single']

In [39]:
df.loc[df["Name"]=="Arpan",["Name","Address","Gender","Status"]]

    Name Address Gender  Status
5  Arpan   Nepal   male  Single

Lets set name as index

In [41]:
df.set_index("Name")

,Age,Gender,Survived,Fare,Address,Age_five_yrs_before,Address_fiveyr_ago,Status,Fare_after_tax
Name,,,,,,,,,
Saval,22,male,1,50,Nepal,17,Nepal,Single,80.0
Nischal,19,Male,1,100,Australia,14,Nepal,Single,160.0
Manil,25,male,1,30,UAE,20,Nepal,Single,48.0
Anush,20,male,1,60,USA,15,Nepal,Single,96.0
Arpan,22,male,NaN,NaN,Nepal,NaN,NaN,Single,NaN

Lets check if it is permmamently changed or not as we have not used loc and inplace= true

In [42]:
df

,Name,Age,Gender,Survived,Fare,Address,Age_five_yrs_before,Address_fiveyr_ago,Status,Fare_after_tax
0,Saval,22,male,1,50,Nepal,17,Nepal,Single,80.0
1,Nischal,19,Male,1,100,Australia,14,Nepal,Single,160.0
2,Manil,25,male,1,30,UAE,20,Nepal,Single,48.0
3,Anush,20,male,1,60,USA,15,Nepal,Single,96.0
5,Arpan,22,male,NaN,NaN,Nepal,NaN,NaN,Single,NaN

Lets change name as index as permanent in df

In [43]:
df.set_index("Name",inplace=True)

In [44]:
df

,Age,Gender,Survived,Fare,Address,Age_five_yrs_before,Address_fiveyr_ago,Status,Fare_after_tax
Name,,,,,,,,,
Saval,22,male,1,50,Nepal,17,Nepal,Single,80.0
Nischal,19,Male,1,100,Australia,14,Nepal,Single,160.0
Manil,25,male,1,30,UAE,20,Nepal,Single,48.0
Anush,20,male,1,60,USA,15,Nepal,Single,96.0
Arpan,22,male,NaN,NaN,Nepal,NaN,NaN,Single,NaN

Lets practice to  acces some values

lets access country of saval

In [46]:
df.loc["Saval","Address"]

'Nepal'

lets use iloc and access gender of manil

In [49]:
df.iloc[2,1]

'male'

LETS ADD MULTIPLE COLUMNS AT ONCE

LETS ADD HEIGHT AND WEIGHT

In [51]:
df.loc[:, ["Height", "Weight"]] = [[175, 70], [168, 65],[180, 80],[172, 75],[170, 68]]

In [53]:
df.loc[:,["Height","Weight"]]

         Height  Weight
Name
Saval       175      70
Nischal     168      65
Manil       180      80
Anush       172      75
Arpan       170      68

lets remove last row of arpan

In [55]:
df.drop("Arpan", inplace=True)

/tmp/ipykernel_999/2893454909.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("Arpan", inplace=True)

In [56]:
df

,Age,Gender,Survived,Fare,Address,Age_five_yrs_before,Address_fiveyr_ago,Status,Fare_after_tax,Height,Weight
Name,,,,,,,,,,,
Saval,22,male,1,50,Nepal,17,Nepal,Single,80.0,175,70
Nischal,19,Male,1,100,Australia,14,Nepal,Single,160.0,168,65
Manil,25,male,1,30,UAE,20,Nepal,Single,48.0,180,80
Anush,20,male,1,60,USA,15,Nepal,Single,96.0,172,75

lets understand about .loc and inplace=true

.loc = WHERE / WHICH data

inplace=True = WHETHER to change the original DataFrame

.loc → selects a specific row/column and can change its value.

inplace=True → makes a pandas operation change the original DataFrame.

Sorting → use inplace=True if you want the sorted order saved directly in df.